export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const FETCH_USER = "FETCH_USER";

export const AUTH_LOGOUT = "AUTH_LOGOUT";

//issue
export const READ_ISSUE_START = "READ_ISSUE_START";
export const READ_ISSUE_SUCCESS = "READ_ISSUE_SUCCESS";
export const READ_ISSUE_FAIL = "READ_ISSUE_FAIL";

//COMPUTERS 
export const READ_COMPUTERS_START = "READ_COMPUTERS_START";
export const READ_COMPUTERS_SUCCESS = "READ_COMPUTERS_SUCCESS";
export const READ_COMPUTERS_FAIL = "READ_COMPUTERS_FAIL";
